# Formats all JavaScript, TypeScript, HTML, and CSS files on each push to main

name: Format Code with Prettier

on:
  push:
    branches: [main]
    paths:
      - "src/**.[jt]sx?"
      - "src/**.html"
      - "src/**.css"

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm ci
      - run: npm run format
      - name: Commit formatting changes (if any)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci: Formatted code with Prettier"
