# Lints TypeScript files with ESLint

name: ESLint

on:
  push:
    branches: [main]
    paths:
      - "src/**.tsx?"
  pull_request:
    branches: [main]
    paths:
      - "src/**.tsx?"

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm ci
      - run: npm run lint
