name: Publish Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm ci
      - run: npm run make
      - name: Release Artifact
        uses: ncipollo/release-action@v1
        with:
          artifacts: "out/make/*.exe,out/make/*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
